### ISSUE TITLE
VisDiffBench-release: image path mismatch csv file

### ISSUE THREAD

**Issue by 42x00** [Understanding-Visual-Datasets/VisDiff#3]
VisDiffBench-release: ./data/VisDiffBench/easy/1_a/000001.jpg
PairedImageSets.csv: ./data/VisDiffBench/easy/0_1/000001.jpg
[FixedPairedImageSets.csv](https://github.com/Understanding-Visual-Datasets/VisDiff/files/13644351/PairedImageSets.csv)

VisDiffBench-release: ./data/VisDiffBench/imagenetr/art/n01833805_art_1.jpg
ImageNetR.csv: ./data/visdiff-imagenet-r/imagenet-r/n01833805/art_1.jpg
[FixedImageNetR.csv](https://github.com/Understanding-Visual-Datasets/VisDiff/files/13656536/ImageNetR.csv)
Note: the group `misc` is missing in the released data

VisDiffBench-release: ./data/VisDiffBench/imagenetstar/in_the_forest/n03733281_48.jpg
ImageNetStar.csv: ./data/visdiff-imagenet-star/in_the_forest/n03733281/48.jpg
[FixedImageNetStar.csv](https://github.com/Understanding-Visual-Datasets/VisDiff/files/13656543/ImageNetStar.csv)

**Comment by yuhui-zh15** [comment]
Thanks a lot for the fix @42x00! Incorporated now https://github.com/Understanding-Visual-Datasets/VisDiff/commit/87a69aac042384ddd6faa343e30ab03a841d10ba

**Comment by yuhui-zh15** [comment]
`misc` is removed because it contains many different styles.
