### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by jmetzen** [Understanding-Visual-Datasets/VisDiff#6]
Thanks a lot of open-sourcing your code! Could you add a LICENSE file to the repository such that usage conditions are defined? Thanks again!

**Comment by lisadunlap** [comment]
Added! #5 [9afc670](https://github.com/Understanding-Visual-Datasets/VisDiff/commit/9afc6700b6f910cad43e46c78328fb56ebc7259b)
